### ISSUE TITLE
Not compatible with Django > 3 due to reliance on django.utils.six

### ISSUE THREAD

**Issue by rsmith013** [leplatrem/django-sizefield#18]
Proposal:
- remove references to six
- make python >3 only
- Release new major version

**Comment by leplatrem** [comment]
Hello! Would you like write access to this repo to perform these tasks?

**Comment by rsmith013** [comment]
@leplatrem  ok. 
This repo uses travis.org for tests, which is deprecated. Do you have any issue with it moving to github actions?

**Comment by leplatrem** [comment]
> This repo uses travis.org for tests, which is deprecated. Do you have any issue with it moving to github actions?

Oh, yes of course! Feel free!

**Comment by variable** [comment]
Hi guys,

I see tag `2.0` but it's not on pypi, any ideas when the version will be on pypi please?

**Comment by leplatrem** [comment]
I reinvited @rsmith013 to the pypi repo. The invite had expired.

**Comment by variable** [comment]
Are you able to push to Pypi repo yourself? It's currently blocking my project to upgrade to Django 3, I might have to roll my own version on my private pypi if this is not getting resolved soon.

**Comment by leplatrem** [comment]
I just pushed it to unblock you ;)

**Comment by variable** [comment]
Nice thank you very much.
