### ISSUE TITLE
Django 4.0 support

### ISSUE THREAD

**Issue by hagbarddenstore** [leplatrem/django-sizefield#22]
Django 4.0 deprecated the use of `from django.utils.translation import ugettext_lazy as _` and the new recommended approach is `from django.utils.translation import gettext_lazy as _` according to this source https://forum.djangoproject.com/t/importerror-cannot-import-name-ugettext-lazy-from-django-utils-translation/10943/2.

**Comment by leplatrem** [comment]
Open a pull-request ;)

**Comment by hagbarddenstore** [comment]
> Open a pull-request ;)

Done!

**Comment by techdragon** [comment]
Can this get merged?
